=== terraframe/geoprism-registry/georegistry-server/src/main/resources/xsd/cgr.xsd
<!--

    Copyright (c) 2022 TerraFrame, Inc. All rights reserved.

    This file is part of Geoprism Registry(tm).

    Geoprism Registry(tm) is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    Geoprism Registry(tm) is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with Geoprism Registry(tm).  If not, see <http://www.gnu.org/licenses/>.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- The root element of the xml schema -->
  <xs:element name="CGR" type="rootOptions" />
  <xs:complexType name="rootOptions">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="organization" type="organization" />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="organization">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="type" type="type" />
        <xs:element name="business-type" type="business-type" />
        <xs:element name="hierarchy" type="hierarchy" />
        <xs:element name="dag" type="graph" />
        <xs:element name="undirected-graph" type="graph" />
        <xs:element name="business-edge" type="business-edge" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="hierarchy">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="child" type="node" minOccurs="1" />
      </xs:choice>
    </xs:sequence>  
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
    <xs:attribute name="progress" type="xs:string" use="optional" />
    <xs:attribute name="acknowledgement" type="xs:string" use="optional" />
    <xs:attribute name="disclaimer" type="xs:string" use="optional" />
    <xs:attribute name="accessConstraints" type="xs:string" use="optional" />
    <xs:attribute name="useConstraints" type="xs:string" use="optional" />
    <xs:attribute name="extends" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="business-edge">
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
    <xs:attribute name="parentTypeCode" type="xs:string" use="optional" />
    <xs:attribute name="childTypeCode" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="graph">
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="group-item">
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="type">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="attributes" type="attributes" minOccurs="0" />
        <xs:element name="group-item" type="group-item" minOccurs="0" maxOccurs="unbounded" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
    <xs:attribute name="visibility" type="visibility" use="optional" />
    <xs:attribute name="geometryType" type="geometryType" use="required" />
    <xs:attribute name="isGeometryEditable" type="xs:boolean" />
    <xs:attribute name="isGroup" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="business-type">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="attributes" type="attributes" minOccurs="0" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required" />
    <xs:attribute name="label" type="xs:string" use="required" />
    <xs:attribute name="description" type="xs:string" use="optional" />
    <xs:attribute name="labelAttribute" type="xs:string" use="optional" />
  </xs:complexType>
  <xs:complexType name="node">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="child" type="node" minOccurs="0" />
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required" />
  </xs:complexType>
  <!-- ************************************** ATTRIBUTE DEFINITIONS ****************************************** -->
  <!-- A list of all possible attributes -->
  <xs:complexType name="attributes">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="text" type="text" />
      <xs:element name="boolean" type="boolean" />
      <xs:element name="integer" type="integer" />
      <xs:element name="decimal" type="decimal" />
      <xs:element name="date" type="date" />
      <xs:element name="term" type="term" />
      <xs:element name="classification" type="classification" />
    </xs:choice>
  </xs:complexType>
  <!-- Common Attributes of all attributes -->
  <xs:attributeGroup name="attribute">
    <!-- name: The name of the attribute -->
    <xs:attribute name="code" type="xs:string" use="required" />
    <!-- label:The display label of the attribute -->
    <xs:attribute name="label" type="xs:string" />
    <!-- description: A description of the purpose of attribute -->
    <xs:attribute name="description" type="xs:string" />
  </xs:attributeGroup>
  <xs:complexType name="text">
    <xs:attributeGroup ref="attribute" />
  </xs:complexType>
  <xs:complexType name="term">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="option">
        <xs:complexType>
          <xs:attribute name="code" type="xs:string" use="required" />
          <!-- label:The display label of the attribute -->
          <xs:attribute name="label" type="xs:string" />
          <!-- description: A description of the purpose of attribute -->
          <xs:attribute name="description" type="xs:string" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref="attribute" />
  </xs:complexType>
  <xs:complexType name="classification">
    <xs:attributeGroup ref="attributeClassification" />
  </xs:complexType>
  <xs:attributeGroup name="attributeClassification">
    <xs:attributeGroup ref="attribute" />
    <xs:attribute name="root" type="xs:string" use="required" />
    <xs:attribute name="classificationType" type="xs:string" use="required" />
  </xs:attributeGroup>
  <xs:attributeGroup name="attributeDec">
    <xs:attributeGroup ref="attribute" />
    <xs:attribute name="precision" type="xs:integer" />
    <xs:attribute name="scale" type="xs:integer" />
  </xs:attributeGroup>
  <!-- Represents a Boolean object in the database -->
  <xs:complexType name="boolean">
    <xs:attributeGroup ref="attribute" />
  </xs:complexType>
  <!-- Represents a Double object in the database -->
  <xs:complexType name="integer">
    <xs:attributeGroup ref="attribute" />
  </xs:complexType>
  <!-- Represents a Decimal object in the database -->
  <xs:complexType name="decimal">
    <xs:attributeGroup ref="attributeDec" />
  </xs:complexType>
  <!-- Represents a Date object in the database -->
  <xs:complexType name="date">
    <xs:attributeGroup ref="attribute" />
  </xs:complexType>
  <xs:simpleType name="visibility">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PRIVATE" />
      <xs:enumeration value="PUBLIC" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="geometryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="POINT" />
      <xs:enumeration value="LINE" />
      <xs:enumeration value="POLYGON" />
      <xs:enumeration value="MIXED" />      
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== terraframe/geoprism-registry/georegistry-test/src/test/resources/xml/test-domain.xml
<!--



-->
<CGR xsi:noNamespaceSchemaLocation="classpath:xsd/cgr.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <organization code="TEST_ORG">
    <type code="TEST_VILLAGE" label="Test Village" description="Test Village Description" visibility="PUBLIC"
          geometryType="POINT" isGeometryEditable="false">
      <attributes>
        <text code="TEST_TEXT" label="Test Text" description="Test Text Description"/>
        <boolean code="TEST_BOOLEAN" label="Test Boolean" description="Test Boolean Description"/>
        <integer code="TEST_INTEGER" label="Test Integer" description="Test Integer Description"/>
        <decimal code="TEST_DECIMAL" label="Test Decimal" description="Test Decimal Description" precision="10"
                 scale="2"/>
        <integer code="TEST_DATE" label="Test Date" description="Test Date Description"/>
        <classification code="TEST_CLASSIFICATION" label="Test Classification"
                        description="Test Text Classification" classificationType="TEST_PROG"
                        root="Test_Classification"/>
      </attributes>
      <group-item code="TEST_GI" label="Test GI" description="Test GI"/>
    </type>
    <type code="TEST_DISTRICT" label="Test District" description="Test District" visibility="PUBLIC"
          geometryType="POINT" isGeometryEditable="false">
    </type>
    <hierarchy code="TEST_HIERARCHY" label="Test Hierarchy" description="Test Hierarchy Description"
               progress="Test Progress" disclaimer="Test Disclaimer" accessConstraints="Test Access Constraints"
               useConstraints="Test Use Constraints" acknowledgement="Test Acknowledgement">
      <child code="TEST_DISTRICT">
        <child code="TEST_VILLAGE"/>
      </child>
    </hierarchy>

    <business-type code="BUSINESS_POP" label="Business Pop" description="Business Pop Description"
                   labelAttribute="TEST_TEXT">
      <attributes>
        <text code="TEST_TEXT" label="Test Text" description="Test Text Description"/>
        <boolean code="TEST_BOOLEAN" label="Test Boolean" description="Test Boolean Description"/>
        <integer code="TEST_INTEGER" label="Test Integer" description="Test Integer Description"/>
        <decimal code="TEST_DECIMAL" label="Test Decimal" description="Test Decimal Description" precision="10"
                 scale="2"/>
        <date code="TEST_DATE" label="Test Date" description="Test Date Description"/>
        <classification code="TEST_CLASSIFICATION" label="Test Classification"
                        description="Test Text Classification" classificationType="TEST_PROG"
                        root="Test_Classification"/>
      </attributes>
    </business-type>
    <business-type code="BUSINESS_CHILD" label="Business Child" description="Business Child">
    </business-type>

    <business-edge code="BUS_EDGE" label="Business Edge" description="Business Edge" parentTypeCode="BUSINESS_POP"
                   childTypeCode="BUSINESS_CHILD">
    </business-edge>

    <business-geoobject-edge code="BUS_GEO_EDGE" label="Business Geo Edge" description="Business Geo Edge" typeCode="BUSINESS_POP"
                   direction="PARENT">
    </business-geoobject-edge>
    
  </organization>

</CGR>
